### PR TITLE
feat: update .clang-uml

### PR DESCRIPTION
**Pull request by tiankaima**
use GitHub Action to auto generate uml & png files

### CODE REVIEW

**Comment by tiankaima** [comment]
~~I've added @zhehaoli1999 as a contributor to my own hw repo for a preview on how this GitHub Action runs. Check your inbox, agree and go to this repo: <https://github.com/tiankaima/USTC_CG_24_HW>~~

~~An example GitHub Action log could be found here: <https://github.com/tiankaima/USTC_CG_24_HW/actions/runs/8298915363>~~

Example: <https://github.com/tiankaima/USTC_CG_24/actions/runs/8298956594>

**Comment by tiankaima** [comment]
Example output: 
[diagrams.zip](https://github.com/USTC-CG/USTC_CG_24/files/14617903/diagrams.zip)

**Comment by suchiwz** [comment]
Thank you for your pull request and update of 'clang-uml' in GitHub Actions. 

Currently, the diagrams are being exported in PNG format, which is good for compatibility. However, considering scalability and clarity, especially for documentation and printing purposes, exporting diagrams in a vector format like SVG or PDF would be beneficial.

Could we consider adding support for SVG or PDF exports? For PDF, maybe we could adjust the GitHub Actions workflow with:

'''
for f in ./*.puml; do
  plantuml -tpdf $f
done
'''

This change would enhance the flexibility and utility of our UML diagrams. Thanks again for your contribution, and we look forward to your update.

**Comment by suchiwz** [comment]
Thank you for your pull request and update of `clang-uml` in GitHub Actions. 

Currently, the diagrams are being exported in PNG format, which is good for compatibility. However, considering scalability and clarity, especially for documentation and printing purposes, exporting diagrams in a vector format like SVG or PDF would be beneficial.

Could we consider adding support for SVG or PDF exports? For PDF, maybe we could adjust the GitHub Actions workflow with:

```
for f in ./*.puml; do
plantuml -tpdf $f
done
```

This change would enhance the flexibility and utility of our UML diagrams. Thanks again for your contribution, and we look forward to your update.

**Comment by tiankaima** [comment]
> Thank you for your pull request and update of `clang-uml` in GitHub Actions.
> 
> Currently, the diagrams are being exported in PNG format, which is good for compatibility. However, considering scalability and clarity, especially for documentation and printing purposes, exporting diagrams in a vector format like SVG or PDF would be beneficial.
> 
> Could we consider adding support for SVG or PDF exports? For PDF, maybe we could adjust the GitHub Actions workflow with:
> 
> ```
> for f in ./*.puml; do
> plantuml -tpdf $f
> done
> ```
> 
> This change would enhance the flexibility and utility of our UML diagrams. Thanks again for your contribution, and we look forward to your update.

Done. See <https://github.com/tiankaima/USTC_CG_24/actions/runs/8300667884> LGTM

```plain
tiankaima@manjaro-laptop in export
$ tree .
.
├── 1_MiniDraw.png
├── 1_MiniDraw.puml
├── 1_MiniDraw.svg
├── 2_ImageWarping.png
├── 2_ImageWarping.puml
├── 2_ImageWarping.svg
├── 3_PoissonImageEditing.png
├── 3_PoissonImageEditing.puml
└── 3_PoissonImageEditing.svg

1 directory, 9 files
```

For GitHub starters in class, GitHub Free would offer 1k minute action runtime.(If I recall correctly?), so plenty for build like this and thus I didn't cache stuff like apt packages.

Had I not reinstalled the system did I realize the pain to go through installing clang-uml on a Windows/macOS system. Initially I went for docker builds, but it occurs to me GitHub Action artifacts would have been a much better solution for beginners.

Upon another homework release, one could simply copy-paste the `.clang-uml` file with a slight edit (Like in this PR). (Or I'll just open another PR :smile: )

Enjoy a nice weekend.

**Comment by tiankaima** [comment]
Any updates?

**Comment by suchiwz** [comment]
Merged. Thank you!

**Pull request merged**
