### PR TITLE
Create .clang-uml for non-vs users

### PR DESCRIPTION
**Pull request by tiankaima**
HW1 requires a class-diagram. For non Visual Studio users this might be painful since most IDE don't provide this util, or one might want a better tool than screenshot.

A tool to help this could be found [here](https://github.com/bkryza/clang-uml).

With this PR I'm uploading a `.clang-uml` config file for this tool.

Setup guide:
1. Install clang-uml, [docs](https://github.com/bkryza/clang-uml/blob/master/docs/installation.md)
    1. For Windows users you can direcly download a exe package
    2. For Linux & macOS users, a manual `make release` and `make install` might be required
3. add `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ` after cmake commands
4. change cmake build dir to `./build`, or modify `complication_database_dir` (in `.clang-uml`) to your build dir
5. Install `plantuml`. Use a package manager for this, don't manually install jar package unless you'd have to.
    1. For Arch Users: using [AUR](https://archlinux.org/packages/extra/any/plantuml/), so `yay -S plantuml`
    2. For macOS Users, `brew install plantuml`, homebrew setup guide: [tuna mirror](https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/) [ustc mirror](https://mirrors.ustc.edu.cn/help/brew.git.html)
    3. For Windows Users, `choco install plantuml`, chocolatey install guide: [here](https://chocolatey.org/install)
6. Run `plantuml ./build/1_MiniDraw.quml`

Preview:
End result looks something like this:
model

### CODE REVIEW

**Comment by zhehaoli1999** [comment]
Looks great! but I guess most students are not familiar with AUR, could you please add a short tutorial on how to generate this diagram on Windows OS?

**Comment by tiankaima** [comment]
> Looks great! but I guess most students are not familiar with AUR, could you please add a short tutorial on how to generate this diagram on Windows OS?

Updated in this PR. Shall I provide a Chinese version document ant put it in `Software/` (If future homeworks still requires a class-diagram?)

**Comment by zhehaoli1999** [comment]
I found the emails from `notifications@github.com` are placed into Spam folders instead of Inbox in my mailbox... anyway, this is fixed. 

Yes, it would be great if you could provide a brief Chinese version document in `Software/`, and I will then merge this PR into main branch.

**Comment by tiankaima** [comment]
> I found the emails from `notifications@github.com` are placed into Spam folders instead of Inbox in my mailbox... anyway, this is fixed.
> 
> Yes, it would be great if you could provide a brief Chinese version document in `Software/`, and I will then merge this PR into main branch.

The docs is written in GitHub flavor markdown, here's a preview: <https://github.com/tiankaima/USTC_CG_24/blob/patch-1/Softwares/Clang-uml.md>

[Another tweak](https://github.com/tiankaima/USTC_CG_24/commit/79d128e0828b6304dc94a690d40c0ab52230724d#diff-53342635843c8e42030474e8f58fa4f5201fa4e997ec570372c8f4fb6d65bcc0R11) is to `Framework2D/CMakeLists.txt` directly so no need to edit `cmake -D...` in IDE settings. 

I hope this clear things up and believe it's ready to merge.

**Pull request merged**
